=== ufal/TrEd/tredlib/contrib/ValLex/vallex.dtd
<!-- ahoj -->
<!ELEMENT valency_lexicon (head, body, tail?)>
<!ATTLIST valency_lexicon
            owner IDREF #REQUIRED>

<!ELEMENT head (global_history, list_of_users)>

<!-- elementy forbid slouzi k zablokovani identifikatoru ramcu a slov -->
<!ELEMENT tail (forbid+)>
<!ELEMENT forbid EMPTY>
<!ATTLIST forbid forbidden_ID ID #REQUIRED >


<!ELEMENT body (word+)>



<!-- to, co se se slovnikem provadelo jako s celkem, 
napr. automaticke transformace formatu nebo dat, prilevani dat z jinych zdroju atd.;
pokud se nekdy prileji dalsi ramce, bude z global_history jasne, co vsechno s nimi
udelat, taky merge -->

<!ELEMENT global_history (global_event+)>   
<!ELEMENT global_event (#PCDATA)> <!-- obsahem elementu je slovni popis zmeny -->
<!ATTLIST global_event 
               time_stamp CDATA #REQUIRED
               author CDATA #REQUIRED   
            > 
                

<!-- zaznam v list_of_users maji jen ti, kteri maji pravo data menit -->
<!ELEMENT list_of_users (user+)>   
<!ELEMENT user EMPTY>  
<!-- user: radeji zkratka, ne cislo -->
<!ATTLIST user 
             name CDATA #REQUIRED
             user_ID ID  #REQUIRED           
             annotator (YES|NO) "NO"
             reviewer (YES|NO) "NO"
           >
<!-- z anotatora muze byt casem reviewer, i reviewer ale muze delat
obycejnou anotacni praci (napr.zalozeni ramce), proto musi mit spolecny namespace -->

<!-- ================================================== -->


<!ELEMENT word (problems?, note?, valency_frames)>
<!-- lemma: "hole" lemma, bez indexu, ale se "se"!!! - rozdil od ATS!-->
<!ATTLIST word lemma CDATA #REQUIRED   
               POS (V|A|N|D)  "V"
               word_ID ID  #REQUIRED           
       >
<!ELEMENT problems (problem+)>
<!ELEMENT problem (#PCDATA)>
<!ATTLIST problem 
               author IDREF #REQUIRED
               solved (YES|NO) "NO"> 
<!-- rozdil mezi note a postponed je ten, ze note obsahuje jen libovolnou doplnkovou informaci,
zatimco poznamka v postponed indikuje, ze to slovo je rozpracovane 
a je potreba ho nejak doresit-->      

<!-- pp: pridavam moznost bez ramcu, napr. je mozne naplnit slovnik nejprve slovesy,
 a teprve pak k nim doplnovat ramce -->
<!ELEMENT valency_frames (frame*)>
<!ELEMENT frame (example, note?, problems?, frame_elements, local_history )>
<!ATTLIST frame
             frame_ID ID #REQUIRED
             old_frame_ID CDATA #IMPLIED
             reciprocity (none|ACT-PAT|ACT-ADDR) "none" 
             control (none|PAT|ADDR) "none"                  
             used CDATA "0"
             hereditary_used CDATA "0"
             status (active|reviewed|substituted|obsolete|deleted) "active"
             substituted_with IDREFS #IMPLIED
          >   
          
<!ELEMENT example (#PCDATA)>   
<!ELEMENT note (#PCDATA)>   
          
<!ELEMENT frame_elements (element*)>  

<!ELEMENT element (form*)>  
<!-- pokud neni vevnitr zadna forma, povazuje se realizace za arbitrary -->  

<!-- functor: "three dashes" means form specification for the governing word 
     it is a dirty hack, but all possibly clean solutions would probably break
     most of the current code
-->
<!ATTLIST element 
       functor  (---|ACT|PAT|ADDR|EFF|ORIG|ACMP|ADVS|AIM|APP|APPS|AUTH|
                 ATT|BEN|CAUS|CNCS|COMPL|COND|CONJ|CONFR|CONTRA|CONTRD|CPR|CRIT|
                 CSQ|CTERF|DENOM|DES|DIFF|DIR1|DIR2|DIR3|DISJ|CPHR|DPHR|
                 ETHD|EXT|FPHR|GRAD|HER|ID|INTF|INTT|
                 LOC|MANN|MAT|MEANS|MOD|NA|NORM|PAR|PARTL|PN|PREC|PRED|REAS|
                 REG|RESL|RESTR|RHEM|RSTR|SUBS|TFHL|TFRWH|THL|THO|TOWH|
                 TPAR|TSIN|TTILL|TWHEN|VOC|VOCAT|SENT) #REQUIRED  
       type (oblig|non-oblig) "non-oblig"
       forms CDATA #IMPLIED
       orig_type CDATA #IMPLIED
     > 

<!ELEMENT form (typical | elided | recip | state | (parent?, node*, (parentpos, node*)?))>  
<!ATTLIST form 
       abbrev         CDATA #IMPLIED
>

<!ELEMENT typical EMPTY>
<!ELEMENT elided EMPTY>
<!ELEMENT recip EMPTY>
<!ELEMENT state EMPTY>

<!-- constrainty na rodice slovesa -->
<!ELEMENT parent (node)>

<!-- element urcuje pozici rodice vuci zavislym uzlum -->
<!ELEMENT parentpos EMPTY>


<!-- pos: f - infinitiv, pos: s - prima rec -->
<!ELEMENT node (node*)>
<!ATTLIST node
        lemma         CDATA #IMPLIED
        neg           (negative|unspecified) "unspecified"
        form          CDATA #IMPLIED
        pos           (a|d|i|n|j|v|u|f|s|c) #IMPLIED
        gen           (F|M|I|N) #IMPLIED
        num           (S|P) #IMPLIED
        deg           (1|2|3) #IMPLIED
        case          (1|2|3|4|5|6|7) #IMPLIED
        agreement     (0|1) "0"
        inherits      (0|1) "0"
        tagpos1       CDATA #IMPLIED
        tagpos2       CDATA #IMPLIED
        tagpos3       CDATA #IMPLIED
        tagpos4       CDATA #IMPLIED
        tagpos5       CDATA #IMPLIED
        tagpos6       CDATA #IMPLIED
        tagpos7       CDATA #IMPLIED
        tagpos8       CDATA #IMPLIED
        tagpos9       CDATA #IMPLIED
        tagpos10      CDATA #IMPLIED
        tagpos11      CDATA #IMPLIED
        tagpos12      CDATA #IMPLIED
        tagpos13      CDATA #IMPLIED
        tagpos14      CDATA #IMPLIED
        tagpos15      CDATA #IMPLIED
>

<!-- v XML datech se sice bude pouzivat cely morfologicky tag, ale na anotatora
se to bude tvari "postaru", napr. na+4,infin.,adverb., atd. -->      
    
<!ELEMENT local_history (local_event+)>
<!ELEMENT local_event EMPTY>  
<!-- time_stamp: okamzik, kdy clovek provedl nebo potvrdil zmenu -->
<!-- author: identifikator anotatora nebo reviewera, nebo empty, jde-li o import -->
<!ATTLIST local_event 
       time_stamp CDATA #REQUIRED 
       type_of_event (create|modify|delete|import|review|obsolete|unreview) #REQUIRED
       author IDREF #IMPLIED
       imported_from CDATA #IMPLIED
    >   
<!-- 1) tady by mozna bylo dobre porusit pravidlo o redundanci a zkopirovat
informaci o tom, jestli byl ramec deleted, nahoru jako atribut elementu frame 
2) drivejsi binarni atributy videnoJPa a videnoMSt zmizi, informace o kontrolach
budou v local_history s typem "reviewed" 


Co se musi rozhodnout:
  - budou -TG anotatori u slovesa oznacovat i kontrolu a reciprocitu?
  - budou TG anotatori pouzivat vicestupnovou skalu obligatornosti,
    nebo jim staci obl/non-obl
  - je jim k necemu informace o zpusobu uziti (primarni, posunuty, frazeolog...)
  - co delat s frazeologismy, ma mit frame element i vlastni lemma (nebo mnozinu lemmat)?

 !!! jestlize se v ramci objevi infinitiv, musi anotator zaskrtnout
 u nektereho slotu kontrolu;
 - zatim neni jasne, jak vypada idealni skala "obligatornosti" (atribut type)

    
  


-->

=== ufal/TrEd/tredlib/contrib/ValLex/out.xml
<?xml version="1.0" encoding="iso-8859-2"?>
<!DOCTYPE valency_lexicon SYSTEM "vallex.dtd">
<valency_lexicon>
 <head>
   <global_history>     
     <global_event time_stamp="...4/10/2001" author="Z.Z.">
        import ramcu z lexicon.xml 
     </global_event>        
   </global_history>     
   <list_of_users>
     <user name="Jarmila Panevov&#225;" user_ID="JPa" annotator="NO" reviewer="YES"/>
     <user name="Zdena Ure&#353;ov&#225;" user_ID="ZUr" annotator="YES" reviewer="NO"/>     
      <user name="Zden&#283;k &#381;abokrtsk&#253;" user_ID="Z.Z." annotator="NO" reviewer="NO"/>     
   </list_of_users>   
 </head>
 <body>    
 <word lemma="chodit" word_ID="w-1" POS="V">
  <valency_frames>
  <frame frame_ID="f-1-1" old_frame_ID="lexicon-A" used="0" status="active">
   <example> chodit n&#283;kam, ... (s n&#283;k&#253;m) p&#283;&#353;ky, chodit-7 od hospody k hospod&#283;, chodit-8 (pravideln&#283;) k psychiatrovi, chod&#237;-9 &#353;patn&#233; zpr&#225;vy z Rwandy </example>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="MANN" type="non-oblig"><form preposition="arbit" tag="..............."/>   </element>
   <element functor="DIR1" type="non-oblig"><form preposition="arbit" tag="..............."/>   </element>
   <element functor="DIR2" type="non-oblig"><form preposition="arbit" tag="..............."/>   </element>
   <element functor="DIR3" type="non-oblig"><form preposition="arbit" tag="..............."/>   </element>
   <element functor="AIM" type="non-oblig"><form preposition="pro" tag="....4.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-1-2" old_frame_ID="lexicon-B" used="0" status="active">	 
   <example>chodit-4 na bor&#367;vky; chodit nakupovat/na n&#225;kup/pro n&#225;kup</example>
   <note>chodit-4 u&#382;&#353;&#237;</note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="INTT" type="oblig"><form tag="vf............."/><form preposition="na+Acc" tag="..............."/>   </element>
   <element functor="BEN" type="non-oblig"><form tag="....3.........."/><form preposition="pro" tag="....4.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-1-3" old_frame_ID="lexicon-C" used="0" status="active">
   <example> chodit s n&#283;k&#253;m; Jana a Marie spolu chod&#237; </example>
   <note> frazeolog. (chodit-8 &#353;ir&#353;&#237;) = na rande </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="ACMP" type="oblig"><form preposition="s" tag="....7.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-1-4" old_frame_ID="lexicon-D" used="0" status="active">
   <example> chodit za ma&#353;karu, jako ma&#353;kara </example>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="PAT" type="oblig"><form preposition="za" tag="....4.........."/><form preposition="jako" tag="....1.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-1-5" old_frame_ID="lexicon-E" used="0" status="active">
   <example> chodit otrhan&#253;, v kr&#225;sn&#253;ch &#353;atech </example>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="COMPL" type="non-oblig"><form preposition="arbitr" tag="..............."/>   </element>
   <!--example> chodit na něco = ujídat </example-->
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-1-6" old_frame_ID="lexicon-E1" used="0" status="active">
   <example> chodit bez chyby (o stroji) </example>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="MANN" type="non-oblig"><form preposition="arbitr" tag="..............."/>   </element>
   <!-- example> chodit na něco = ujídat </example -->
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 

  </valency_frames>
 </word>
 <word lemma="chyb&#283;t" word_ID="w-2" POS="V">
  <valency_frames>
  <frame frame_ID="f-2-1" old_frame_ID="lexicon-A" used="0" status="active">
   <example> n&#283;komu n&#283;co/n&#283;kdo chyb&#237;; chyb&#237; si (=jeden druh&#233;mu) </example>
   <note>  alter </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/><form tag="vf............."/><form preposition="&#382;e" tag="..............."/>   </element>
   <element functor="ADDR" type="oblig"><form tag="....3.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-2-2" old_frame_ID="lexicon-A1" used="0" status="active">
   <example> n&#283;kde n&#283;co chyb&#237; (alter) </example>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/><form tag="vf............."/><form preposition="&#382;e" tag="..............."/>   </element>
   <element functor="LOC" type="oblig"><form preposition="arbit" tag="..............."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 

  </valency_frames>
 </word>
 <word lemma="c&#237;tit" word_ID="w-3" POS="V">
  <valency_frames>
  <frame frame_ID="f-3-1" old_frame_ID="lexicon-A" used="0" status="active">
   <example> c&#237;t&#237; v&#367;ni / &#382;e n&#283;co von&#237; / jak n&#283;co von&#237;; psi se c&#237;t&#237; (navz&#225;jem, na d&#225;lku) </example>
   <note> "slov. akuzativ"; &#353;ir&#353;&#237; (i c&#237;tit~feel) </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="PAT" type="oblig"><form tag="....4.........."/><form preposition="&#382;e" tag="..............."/><form preposition="jak" tag="..............."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-3-2" old_frame_ID="lexicon-B" used="0" status="active">
   <example> c&#237;til Karla vej&#237;t; c&#237;tili se p&#345;ich&#225;zet </example>
   <note> "slov. akuzativ"; &#353;ir&#353;&#237; (i c&#237;tit~feel) </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="PAT" type="oblig"><form tag="....4.........."/>   </element>
   <element functor="EFF" type="oblig"><form tag="vf............."/><form preposition="jak" tag="..............."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-3-3" old_frame_ID="lexicon-C" used="0" status="active">
   <example> c&#237;tit s trp&#283;j&#237;c&#237;mi; souc&#237;tili spolu (jeden s druh&#253;m)
   </example>
   <note> =souc&#237;tit </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="PAT" type="oblig"><form preposition="s" tag="....7.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 

  </valency_frames>
 </word>
 <word lemma="c&#237;tit se" word_ID="w-4" POS="V">
  <valency_frames>
  <frame frame_ID="f-4-1" old_frame_ID="lexicon-A" used="0" status="active">
   <example> c&#237;t&#237; se (b&#253;t) mlad&#253;/mlad&#253;m/jako mlad&#237;k </example>
   <note> tantum; pova&#382;ovat se za n&#283;jak&#233;ho </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="PAT" type="oblig"><form tag="....7.........."/><form tag="vf............."/><form preposition="Adj" tag="..............."/><form preposition="jako" tag="....1.........."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
   </local_history>   
 </frame> 
  <frame frame_ID="f-4-2" old_frame_ID="lexicon-A1" used="0" status="active">
   <example> c&#237;t&#237; se sta&#345;e </example>
   <note> tantum; jak mu bylo </note>
  <frame_elements>
   <element functor="ACT" type="oblig"><form tag="....1.........."/>   </element>
   <element functor="MANN" type="oblig"><form preposition="arbit" tag="..............."/>   </element>
  </frame_elements>
   <local_history>
     <local_event time_stamp="4.10.2001+presny cas" type_of_event="import" author="Z.Z." imported_from="lexicon.xml"/>
